title: Thomas Pedbereznak
# email:
description: >
  A personal website for Thomas Pedbereznak (Tom Ped).
baseurl: ""
url: "https://www.tomped.com"
linkedin_id: tpedbereznak
github_username: TomPed

collections:
  work:
    output: false
  sites:
    output: false

sass:
    style: compressed

markdown: kramdown
