title: Thomas Pedbereznak
# email:
description: >
  A personal website for Thomas Pedbereznak (Tom Ped).
baseurl: ""
permalink: /404.html
url: "http://tomped.com"
linkedin_id: tpedbereznak
github_username: TomPed

collections:
  - work

sass:
    style: compressed

markdown: kramdown

include: ["js/highlight.pack.js"]
