title: Thomas Pedbereznak
email: tomped123456789@gmail.com
description: >
  A personal website for Thomas Pedbereznak (Tom Ped).
baseurl: ""
permalink: /404.html
url: "http://tomped.com"
facebook_id: TommyPed
linkedin_id: tpedbereznak
twitter_username: tomped1
instagram_username: tomped_e
youtube_channel: UCHUXOpIyLyKGkt1BCK-hw9g
google_plus_id: TomPed
github_username: TomPed

collections:
  - work

# Build settings
markdown: kramdown
