# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Thomas Pedbereznak
email: tomped123456789@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A personal website for Thomas Pedbereznak (Tom Ped).
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://tomped.github.io" # the base hostname & protocol for your site
facebook_id: TommyPed
linkedin_id: tpedbereznak
twitter_username: tomped1
instagram_username: tomped_e
youtube_channel: UCHUXOpIyLyKGkt1BCK-hw9g
google_plus_id: TomPed
github_username: TomPed

collections:
  - work

# Build settings
markdown: kramdown
